name: vosk_flutter_2
description: Flutter plugin for offline speech recognition using the Vosk speech recognition toolkit.
version: 1.0.5
homepage: https://alphacephei.com/
repository: https://github.com/bilal-codingkey/vosk-flutter

environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  archive: ^3.4.2
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_config: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  pubspec_parse: ^1.2.3

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.3.3
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

ffigen:
  name: VoskLibrary
  output: "lib/src/generated_vosk_bindings.dart"
  headers:
    entry-points:
      - "vosk-api/src/vosk_api.h"

flutter:
  plugin:
    platforms:
      android:
        package: org.vosk.vosk_flutter
        pluginClass: VoskFlutterPlugin
